idl: q18.pro
	.run q18.pro
	$(IDL_DIR)/bin/idl -e "command"  

#where command is the name of
# your idl procedure file

fortran: q18.f90
	f95 -o ex_fortran q18.f90

c: q18.c
	cc -o ex_c q18.c

python: q18.py
	python q18.py
